// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChooseArea: typeof import('./src/components/choose-area/ChooseArea.vue')['default']
    ChooseIcon: typeof import('./src/components/choose-icon/ChooseIcon.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconEdit: typeof import('element-plus/es')['ElIconEdit']
    ElIconWatermelon: typeof import('element-plus/es')['ElIconWatermelon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    NavHeader: typeof import('./src/components/layout/components/NavHeader.vue')['default']
    NavMenu: typeof import('./src/components/layout/components/NavMenu.vue')['default']
  }
}

export { }
